---
- name: INSTALAÇÃO E CONFIGURAÇÃO DO SISTEMA
  hosts: all
  gather_facts: yes
  become: false

  tasks:
  - name: system-update | Removendo ferramentas não necessárias
    dnf:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - gnome-boxes
      - libreoffice*
      - evolution
    become: true

  - name: system-update | Instalando ferramentas de apoio
    dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - fedora-workstation-repositories
      - vim
      - git
      - python3-psutil
      - tilix
      - toolbox
      - origin-clients
      - python3-pip
      - podman
      - source-to-image
    become: true

  - name: system-update | Configurando o Terminal Tilix
    dconf:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
      state: present
    with_items:
    - { key: "/com/gexperts/Tilix/copy-on-select", value: "true" }
    - { key: "/com/gexperts/Tilix/paste-strip-first-char", value: "true" }
    - { key: "/com/gexperts/Tilix/theme-variant", value: "'dark'" }
    - { key: "/com/gexperts/Tilix/warn-vte-config-issue", value: "false" }

  - name: system-update | Instalando o navegador Google Chrome
    dnf:
      name: google-chrome-stable
      enablerepo: google-chrome
      state: present
    become: true

  - name: system-update | Gerando chave SSH para o usuário {{ ansible_user_id }}
    user:
      name: "{{ansible_user_id}}"
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_bits: 4096
      force: no